# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-01 15:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BetaTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('tagline', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo_image')),
                ('link', models.URLField(blank=True, max_length=120, null=True)),
                ('app_file', models.FileField(blank=True, null=True, upload_to='app_files')),
                ('region', models.CharField(choices=[(b'North Africa', b'North Africa'), (b'West Africa', b'West Africa'), (b'Central Africa', b'Central Africa'), (b'East Africa', b'East Africa'), (b'South Africa', b'South Africa')], max_length=60)),
                ('country', models.CharField(choices=[(b'Nigeria', b'Nigeria'), (b'Algeria', b'Algeria'), (b'Angola', b'Angola'), (b'Benin', b'Benin'), (b'Botswana', b'Botswana'), (b'Burkina', b'Burkina'), (b'Burundi', b'Burundi'), (b'Cameroon', b'Cameroon'), (b'Cape Verde', b'Cape Verde'), (b'Central African Republic', b'Central African Republic'), (b'Chad', b'Chad'), (b'Comoros', b'Comoros'), (b'Congo', b'Congo'), (b'Congo DRC', b'Congo DRC'), (b'Djibouti', b'Djibouti'), (b'Egypt', b'Egypt'), (b'Equatorial Guinea', b'Equatorial Guinea'), (b'Eritrea', b'Eritrea'), (b'Ethiopia', b'Ethiopia'), (b'Gabon', b'Gabon'), (b'Gambia', b'Gambia'), (b'Ghana', b'Ghana'), (b'Guinea', b'Guinea'), (b'Guinea-Bissau', b'Guinea-Bissau'), (b'Ivory Coast', b'Ivory Coast'), (b'Kenya', b'Kenya'), (b'Lesotho', b'Lesotho'), (b'Liberia', b'Liberia'), (b'Libya', b'Libya'), (b'Madagascar', b'Madagascar'), (b'Malawi', b'Malawi'), (b'Mali', b'Mali'), (b'Mauritania', b'Mauritania'), (b'Mauritius', b'Mauritius'), (b'Morocco', b'Morocco'), (b'Mozambique', b'Mozambique'), (b'Namibia', b'Namibia'), (b'Niger', b'Niger'), (b'Rwanda', b'Rwanda'), (b'Sao Tome and Principe', b'Sao Tome and Principe'), (b'Senegal', b'Senegal'), (b'Seychelles', b'Seychelles'), (b'Sierra Leone', b'Sierra Leone'), (b'Somalia', b'Somalia'), (b'South Africa', b'South Africa'), (b'South Sudan', b'South Sudan'), (b'Sudan', b'Sudan'), (b'Swaziland', b'Swaziland'), (b'Tanzania', b'Tanzania'), (b'Togo', b'Togo'), (b'Tunisia', b'Tunisia'), (b'Uganda', b'Uganda'), (b'Zambia', b'Zambia'), (b'Zimbabwe', b'Zimbabwe')], max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('age_from', models.CharField(max_length=3)),
                ('age_to', models.CharField(max_length=3)),
                ('sex', models.CharField(choices=[(b'All', b'All'), (b'Male', b'Male'), (b'Female', b'Female')], max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[(b'Pending', b'Pending'), (b'Approved', b'Approved'), (b'Declined', b'Declined')], max_length=30)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NewLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_id', models.CharField(max_length=60, unique=True)),
                ('startup', models.CharField(max_length=30)),
                ('tagline', models.CharField(max_length=60)),
                ('home_page', models.ImageField(upload_to='home_page')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='home_page')),
                ('launching', models.DateField(blank=True, null=True)),
                ('category', models.CharField(choices=[(b'APPS', b'APPS'), (b'Advertising', b'Advertising'), (b'Agriculture', b'Agriculture'), (b'Analytics', b'Analytics'), (b'Auto Mobile', b'Auto Mobile'), (b'Auto Parts', b'Auto Parts'), (b'Betting', b'Betting'), (b'Big Data', b'Big Data'), (b'Biotechnology', b'Biotechnology'), (b'Blogging', b'Blogging'), (b'Chat', b'Chat'), (b'Cloud Storage', b'Cloud Storage'), (b'Construction', b'Construction'), (b'Consulting', b'Consulting'), (b'Curate Web', b'Curate Web'), (b'Databases', b'Databases'), (b'Dating', b'Dating'), (b'Deals', b'Deals'), (b'E-Commerce', b'E-Commerce'), (b'Education', b'Education'), (b'Enterprise Software', b'Enterprise Software'), (b'Entertainment', b'Entertainment'), (b'Environment', b'Environment'), (b'Events', b'Events'), (b'Fashion', b'Fashion'), (b'Finance', b'Finance'), (b'Fitness', b'Fitness'), (b'Foods', b'Foods'), (b'Forum', b'Forum'), (b'Gaming', b'Gaming'), (b'Government', b'Government'), (b'Handcraft', b'Handcraft'), (b'Health', b'Health'), (b'Hotels', b'Hotels'), (b'Human Resources', b'Human Resources'), (b'Information Technology', b'Information Technology'), (b'Interior Decoration', b'Interior Decoration'), (b'Internet Security', b'Internet Security'), (b'Internet Services', b'Internet Services'), (b'IoT', b'IoT'), (b'Jobs', b'Jobs'), (b'Legal', b'Legal'), (b'Location Base Services', b'Location Base Services'), (b'Logistics', b'Logistics'), (b'Manufacturing', b'Manufacturing'), (b'Market Place', b'Market Place'), (b'Marketing', b'Marketing'), (b'Media', b'Media'), (b'Message', b'Message'), (b'Mobile', b'Mobile'), (b'Mobile APP', b'Mobile APP'), (b'Mobile Money', b'Mobile Money'), (b'Mobile Payment', b'Mobile Payment'), (b'Music', b'Music'), (b'News', b'News'), (b'Non Profit Organizations', b'Non Profit Organizations'), (b'Oil Servicing', b'Oil Servicing'), (b'Oil and Gas', b'Oil and Gas'), (b'On Demand Services', b'On Demand Services'), (b'Open Source', b'Open Source'), (b'Payments', b'Payments'), (b'Photo Sharing', b'Photo Sharing'), (b'Photography', b'Photography'), (b'Printing', b'Printing'), (b'Programing', b'Programing'), (b'Real Estate', b'Real Estate'), (b'Recruitment', b'Recruitment'), (b'Religion', b'Religion'), (b'Restaurants', b'Restaurants'), (b'Review and Recommendation', b'Review and Recommendation'), (b'SEO', b'SEO'), (b'Search', b'Search'), (b'Shipping', b'Shipping'), (b'Social Media', b'Social Media'), (b'Social Media Marketing', b'Social Media Marketing'), (b'Social Network', b'Social Network'), (b'Software', b'Software'), (b'Sports', b'Sports'), (b'Startups', b'Startups'), (b'Survey', b'Survey'), (b'Telecommunications', b'Telecommunications'), (b'Ticketing', b'Ticketing'), (b'Transportation', b'Transportation'), (b'Travel', b'Travel'), (b'Travel Tourism', b'Travel Tourism'), (b'Venture Capital', b'Venture Capital'), (b'Video', b'Video'), (b'Web Design', b'Web Design'), (b'Web Developer', b'Web Developer'), (b'Web Hosting', b'Web Hosting')], max_length=30)),
                ('description', models.TextField()),
                ('region', models.CharField(choices=[(b'North Africa', b'North Africa'), (b'West Africa', b'West Africa'), (b'Central Africa', b'Central Africa'), (b'East Africa', b'East Africa'), (b'South Africa', b'South Africa')], max_length=60)),
                ('country', models.CharField(choices=[(b'Nigeria', b'Nigeria'), (b'Algeria', b'Algeria'), (b'Angola', b'Angola'), (b'Benin', b'Benin'), (b'Botswana', b'Botswana'), (b'Burkina', b'Burkina'), (b'Burundi', b'Burundi'), (b'Cameroon', b'Cameroon'), (b'Cape Verde', b'Cape Verde'), (b'Central African Republic', b'Central African Republic'), (b'Chad', b'Chad'), (b'Comoros', b'Comoros'), (b'Congo', b'Congo'), (b'Congo DRC', b'Congo DRC'), (b'Djibouti', b'Djibouti'), (b'Egypt', b'Egypt'), (b'Equatorial Guinea', b'Equatorial Guinea'), (b'Eritrea', b'Eritrea'), (b'Ethiopia', b'Ethiopia'), (b'Gabon', b'Gabon'), (b'Gambia', b'Gambia'), (b'Ghana', b'Ghana'), (b'Guinea', b'Guinea'), (b'Guinea-Bissau', b'Guinea-Bissau'), (b'Ivory Coast', b'Ivory Coast'), (b'Kenya', b'Kenya'), (b'Lesotho', b'Lesotho'), (b'Liberia', b'Liberia'), (b'Libya', b'Libya'), (b'Madagascar', b'Madagascar'), (b'Malawi', b'Malawi'), (b'Mali', b'Mali'), (b'Mauritania', b'Mauritania'), (b'Mauritius', b'Mauritius'), (b'Morocco', b'Morocco'), (b'Mozambique', b'Mozambique'), (b'Namibia', b'Namibia'), (b'Niger', b'Niger'), (b'Rwanda', b'Rwanda'), (b'Sao Tome and Principe', b'Sao Tome and Principe'), (b'Senegal', b'Senegal'), (b'Seychelles', b'Seychelles'), (b'Sierra Leone', b'Sierra Leone'), (b'Somalia', b'Somalia'), (b'South Africa', b'South Africa'), (b'South Sudan', b'South Sudan'), (b'Sudan', b'Sudan'), (b'Swaziland', b'Swaziland'), (b'Tanzania', b'Tanzania'), (b'Togo', b'Togo'), (b'Tunisia', b'Tunisia'), (b'Uganda', b'Uganda'), (b'Zambia', b'Zambia'), (b'Zimbabwe', b'Zimbabwe')], max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('url', models.URLField(max_length=120)),
                ('tag', models.CharField(choices=[(b'Online Shopping', b'Online Shopping'), (b'Jobs', b'Jobs'), (b'News', b'News'), (b'Financial Services', b'Financial Services'), (b'Marketing And Advertising', b'Marketing And Advertising'), (b'Social Media', b'Social Media'), (b'Entertainment', b'Entertainment'), (b'Enterprise', b'Enterprise'), (b'Travel And Tourism', b'Travel And Tourism'), (b'Web Development', b'Web Development'), (b'Logistics And Transportion', b'Logistics And Transportion'), (b'Foods', b'Foods'), (b'Sports', b'Sports'), (b'Production', b'Production'), (b'Mobile', b'Mobile'), (b'NGOS', b'NGOS'), (b'Search', b'Search'), (b'Automotive', b'Automotive'), (b'Health', b'Health'), (b'Education', b'Education'), (b'On Demand Services', b'On Demand Services'), (b'Properties', b'Properties'), (b'ICT', b'ICT'), (b'Consulting', b'Consulting'), (b'Startups', b'Startups'), (b'Reviews', b'Reviews'), (b'Government', b'Government'), (b'SMEs', b'SMEs')], max_length=60)),
                ('promoted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[(b'Beta', b'Beta'), (b'Live', b'Live')], max_length=30)),
                ('pending', models.BooleanField(default=True)),
                ('approved', models.BooleanField(default=False)),
                ('declined', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('newest', models.BooleanField(default=False)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60)),
                ('photo', models.ImageField(upload_to='team_photos')),
                ('twitter_handle', models.CharField(blank=True, max_length=120, null=True)),
                ('role', models.CharField(choices=[(b'Founder', b'Founder'), (b'Co-Founder', b'Co-Founder'), (b'Team Member', b'Team Member')], max_length=30)),
                ('startup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beta.Startup')),
            ],
        ),
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[(b'North Africa', b'North Africa'), (b'West Africa', b'West Africa'), (b'Central Africa', b'Central Africa'), (b'East Africa', b'East Africa'), (b'South Africa', b'South Africa')], max_length=60)),
                ('country', models.CharField(choices=[(b'Nigeria', b'Nigeria'), (b'Algeria', b'Algeria'), (b'Angola', b'Angola'), (b'Benin', b'Benin'), (b'Botswana', b'Botswana'), (b'Burkina', b'Burkina'), (b'Burundi', b'Burundi'), (b'Cameroon', b'Cameroon'), (b'Cape Verde', b'Cape Verde'), (b'Central African Republic', b'Central African Republic'), (b'Chad', b'Chad'), (b'Comoros', b'Comoros'), (b'Congo', b'Congo'), (b'Congo DRC', b'Congo DRC'), (b'Djibouti', b'Djibouti'), (b'Egypt', b'Egypt'), (b'Equatorial Guinea', b'Equatorial Guinea'), (b'Eritrea', b'Eritrea'), (b'Ethiopia', b'Ethiopia'), (b'Gabon', b'Gabon'), (b'Gambia', b'Gambia'), (b'Ghana', b'Ghana'), (b'Guinea', b'Guinea'), (b'Guinea-Bissau', b'Guinea-Bissau'), (b'Ivory Coast', b'Ivory Coast'), (b'Kenya', b'Kenya'), (b'Lesotho', b'Lesotho'), (b'Liberia', b'Liberia'), (b'Libya', b'Libya'), (b'Madagascar', b'Madagascar'), (b'Malawi', b'Malawi'), (b'Mali', b'Mali'), (b'Mauritania', b'Mauritania'), (b'Mauritius', b'Mauritius'), (b'Morocco', b'Morocco'), (b'Mozambique', b'Mozambique'), (b'Namibia', b'Namibia'), (b'Niger', b'Niger'), (b'Rwanda', b'Rwanda'), (b'Sao Tome and Principe', b'Sao Tome and Principe'), (b'Senegal', b'Senegal'), (b'Seychelles', b'Seychelles'), (b'Sierra Leone', b'Sierra Leone'), (b'Somalia', b'Somalia'), (b'South Africa', b'South Africa'), (b'South Sudan', b'South Sudan'), (b'Sudan', b'Sudan'), (b'Swaziland', b'Swaziland'), (b'Tanzania', b'Tanzania'), (b'Togo', b'Togo'), (b'Tunisia', b'Tunisia'), (b'Uganda', b'Uganda'), (b'Zambia', b'Zambia'), (b'Zimbabwe', b'Zimbabwe')], max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('age', models.CharField(max_length=3)),
                ('sex', models.CharField(choices=[(b'Male', b'male'), (b'Female', b'Female')], max_length=30)),
                ('social_account', models.URLField()),
                ('your_industry', models.CharField(choices=[(b'Tech', b'Tech'), (b'Telecom', b'Telecom'), (b'Entertainment', b'Entertainment'), (b'Financial', b'Financial'), (b'Student', b'Student'), (b'Government', b'Government'), (b'NGO', b'NGO'), (b'Automobile', b'Automobile'), (b'Religion', b'Religion')], max_length=250)),
                ('confirmation', models.BooleanField(default=False)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestFeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('testing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beta.BetaTest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='signup',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beta.Startup'),
        ),
        migrations.AddField(
            model_name='signup',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beta.Startup'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
