# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-31 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0002_auto_20160714_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('subject', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FAQ', models.TextField(blank=True, null=True)),
                ('about_us', models.TextField(blank=True, null=True)),
                ('join_our_network', models.TextField(blank=True, null=True)),
                ('advertise_with_us', models.TextField(blank=True, null=True)),
                ('our_rules', models.TextField(blank=True, null=True)),
                ('terms_and_conditions', models.TextField(blank=True, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=120)),
                ('address_line_2', models.CharField(blank=True, max_length=120)),
                ('phone_number', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=120)),
                ('pub_date_info', models.DateTimeField(auto_now_add=True)),
                ('mod_date_info', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='startup',
            name='launching',
        ),
        migrations.AlterField(
            model_name='startup',
            name='status',
            field=models.CharField(choices=[(b'private Beta', b'private Beta'), (b'Beta', b'Beta'), (b'Live', b'Live')], max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='signup',
            unique_together=set([('user', 'startup')]),
        ),
    ]
