# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0003_auto_20160831_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='startup',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='declined',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='newest',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='published',
        ),
        migrations.AddField(
            model_name='startup',
            name='pub_status',
            field=models.CharField(blank=True, choices=[(b' ', b' '), (b'Approved', b'Approved'), (b'Declined', b'Declined')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='betatest',
            name='status',
            field=models.CharField(choices=[(b' ', b' '), (b'Approved', b'Approved'), (b'Declined', b'Declined')], max_length=30),
        ),
        migrations.AlterField(
            model_name='startup',
            name='status',
            field=models.CharField(choices=[(b'Under Development', b'Under Development'), (b'Private Beta', b'Private Beta'), (b'Public Beta', b'Public Beta'), (b'Live', b'Live')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
