# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0004_auto_20160907_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betatest',
            name='status',
            field=models.CharField(choices=[(b' ', b' '), (b'Published', b'Published'), (b'Declined', b'Declined')], max_length=30),
        ),
        migrations.AlterField(
            model_name='startup',
            name='pub_status',
            field=models.CharField(blank=True, choices=[(b' ', b' '), (b'Published', b'Published'), (b'Declined', b'Declined')], max_length=30, null=True),
        ),
    ]
