# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-08 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0005_auto_20160907_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betatest',
            name='status',
            field=models.CharField(choices=[(b'Pending', b'Pending'), (b'Published', b'Published'), (b'Declined', b'Declined')], max_length=30),
        ),
        migrations.AlterField(
            model_name='newletter',
            name='email',
            field=models.EmailField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='pub_status',
            field=models.CharField(blank=True, choices=[(b'Pending', b'Pending'), (b'Published', b'Published'), (b'Declined', b'Declined')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='status',
            field=models.CharField(choices=[(b' ', b' '), (b'Under Development', b'Under Development'), (b'Private Beta', b'Private Beta'), (b'Public Beta', b'Public Beta'), (b'Live', b'Live')], max_length=30),
        ),
    ]
