# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-20 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0009_auto_20160919_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='tag',
            field=models.CharField(choices=[(b'Online Shopping', b'Online Shopping'), (b'Entertainment', b'Entertainment'), (b'Enterprise', b'Enterprise'), (b'On Demand Services', b'On Demand Services'), (b'FINSEC', b'FINSEC'), (b'Social Services', b'Social Services')], max_length=60),
        ),
    ]
