# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-23 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0010_auto_20160920_1417'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Defaults',
            new_name='Default',
        ),
        migrations.AlterField(
            model_name='betatest',
            name='region',
            field=models.CharField(choices=[(b'North Africa', b'North Africa'), (b'West Africa', b'West Africa'), (b'Central Africa', b'Central Africa'), (b'East Africa', b'East Africa'), (b'South Africa', b'South Africa')], max_length=60),
        ),
        migrations.AlterField(
            model_name='startup',
            name='region',
            field=models.CharField(choices=[(b'North Africa', b'North Africa'), (b'West Africa', b'West Africa'), (b'Central Africa', b'Central Africa'), (b'East Africa', b'East Africa'), (b'South Africa', b'South Africa')], max_length=60),
        ),
        migrations.AlterField(
            model_name='startup',
            name='startup_id',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='role',
            field=models.CharField(choices=[(b' ', b' '), (b'Founder', b'Founder'), (b'Co-Founder', b'Co-Founder'), (b'Team Member', b'Team Member')], max_length=30),
        ),
        migrations.AlterField(
            model_name='tester',
            name='region',
            field=models.CharField(choices=[(b'North Africa', b'North Africa'), (b'West Africa', b'West Africa'), (b'Central Africa', b'Central Africa'), (b'East Africa', b'East Africa'), (b'South Africa', b'South Africa')], max_length=60),
        ),
    ]
