# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-26 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0011_auto_20160923_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='pub_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
