# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-26 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0012_auto_20160926_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='stat',
            field=models.CharField(choices=[(b'Tech', b'Tech'), (b'Telecom', b'Telecom'), (b'Entertainment', b'Entertainment'), (b'Financial', b'Financial'), (b'Student', b'Student'), (b'Government', b'Government'), (b'NGO', b'NGO'), (b'Automobile', b'Automobile'), (b'Religion', b'Religion')], default='', max_length=30),
            preserve_default=False,
        ),
    ]
