# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-26 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0013_startup_stat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='stat',
        ),
        migrations.AlterField(
            model_name='startup',
            name='status',
            field=models.CharField(choices=[(b'Pending', b'Pending'), (b'Published', b'Published'), (b'Declined', b'Declined')], max_length=30),
        ),
    ]
