from django.conf.urls import url, patterns
from beta import views

#URLS
app_name = 'beta'
urlpatterns = [
    #Index URL. Displays the first page 
    url(r'^$', views.index, name='index'),
    url(r'^beta_details/(?P<ID>.+)/(?P<startup_id>.+)/$', views.beta_details,
         name='beta_details'),
    url(r'^beta_user/$', views.beta_user, name='beta_user'),
    url(r'^beta_user_details/(?P<ID>.+)/(?P<startup_id>.+)/$', views.beta_user_details,
         name='beta_user_details'),
    url(r'^join_testers/$', views.join_testers, name='join_testers'),
    url(r'^submit_beta/$', views.submit_beta, name='submit_beta'),
    url(r'^test_beta/$', views.test_beta, name='test_beta'),
    url(r'^newest/$', views.newest, name='newest'),
    url(r'^signups/(?P<startup_id>.+)/$', views.signups, name='signups'),
    url(r'^testing_app/$', views.testing_app, name='testing_app'),
    url(r'^archives/$', views.archives, name='archives'),
    #url(r'^add_team/$', views.add_team, name='add_team'),
    # url(r'^add_team/(?P<startup_id>.+)/$', views.add_team,
    #      name='add_team'),
    #url(r'^beta_details/(?P<startup_id>.+)/$', views.beta_details, name='beta_details'),
    url(r'^delete_team/(?P<startup_id>.+)/$', views.delete_team,
         name='delete_team'),
    url(r'^edit_beta/(?P<startup_id>.+)/$', views.edit_beta,
         name='edit_beta'),
    url(r'^delete_startup/(?P<startup_id>.+)/$', views.delete_startup,
         name='delete_startup'),
    url(r'^edit_testing/(?P<startup_id>.+)/$', views.edit_testing,
         name='edit_testing'),
    url(r'^signup/(?P<ID>.+)/(?P<startup_id>.+)/$', views.signup, name='signup'),
    url(r'^admin_signups/(?P<startup_id>.+)/$', views.admin_signups, name='admin_signups'),
    url(r'^test_invites/$', views.test_invites, name='test_invites'),
    url(r'^activities/$', views.activities, name='activities'),
    url(r'^regions/(?P<startup_id>.+)/$', views.regions,
         name='regions'),
    url(r'^country/(?P<startup_id>.+)/$', views.country,
         name='country'),
    url(r'^west_africa/$', views.west_africa, name='west_africa'),
    url(r'^east_africa/$', views.east_africa, name='east_africa'),
    url(r'^north_africa/$', views.north_africa, name='north_africa'),
    url(r'^southern_africa/$', views.southern_africa, name='southern_africa'),
    url(r'^central_africa/$', views.central_africa, name='central_africa'),
    url(r'^launching_this_week/$', views.launching_this_week,
        name='launching_this_week'),
    url(r'^startups/$', views.startups, name='startups'),
    url(r'^mystartup/$', views.mystartup, name='mystartup'),
    url(r'^startup/(?P<startup_id>.+)/$', views.startup, name='startup'),
    url(r'^delete_signup/(?P<startup_id>.+)/$', views.delete_signup, name='delete_signup'),
    url(r'^edit_startup/(?P<startup_id>.+)/$', views.edit_startup, name='edit_startup'),
    url(r'^submit_admin_beta/$', views.submit_admin_beta, name='submit_admin_beta'),
    url(r'^contact_us/$', views.contact_us, name='contact_us'),
    url(r'^search/$', views.search, name='search'),
    url(r'^status_search/$', views.status_search, name='status_search'),
    url(r'^admin_search/$', views.admin_search, name='admin_search'),
    url(r'^newsletter/$', views.newsletter, name='newsletter'),
    #url(r'^export_signups/$', views.export_signups, name='export_signups'),
    url(r'^export_signups/(?P<startup_id>.+)/$', views.export_signups, name='export_signups'),

    ]